'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Convertor.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error : .
        '''</summary>
        Friend ReadOnly Property Form1_BackgroundWorker1_DoWork_Error___() As String
            Get
                Return ResourceManager.GetString("Form1_BackgroundWorker1_DoWork_Error___", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error : This type of Audio/Video is not supported.
        '''</summary>
        Friend ReadOnly Property Form1_BackgroundWorker1_DoWork_Error___This_type_of_Audio_Video_is_not_supported() As String
            Get
                Return ResourceManager.GetString("Form1_BackgroundWorker1_DoWork_Error___This_type_of_Audio_Video_is_not_supported", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Completed Successfully.
        '''</summary>
        Friend ReadOnly Property Form1_BackgroundWorker1_RunWorkerCompleted_Completed_Successfully() As String
            Get
                Return ResourceManager.GetString("Form1_BackgroundWorker1_RunWorkerCompleted_Completed_Successfully", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ready !.
        '''</summary>
        Friend ReadOnly Property Form1_BackgroundWorker1_RunWorkerCompleted_Ready__() As String
            Get
                Return ResourceManager.GetString("Form1_BackgroundWorker1_RunWorkerCompleted_Ready__", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stopped.
        '''</summary>
        Friend ReadOnly Property Form1_BackgroundWorker1_RunWorkerCompleted_Stopped() As String
            Get
                Return ResourceManager.GetString("Form1_BackgroundWorker1_RunWorkerCompleted_Stopped", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stop.
        '''</summary>
        Friend ReadOnly Property Form1_Button10_Click__Stop() As String
            Get
                Return ResourceManager.GetString("Form1_Button10_Click__Stop", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Convert All.
        '''</summary>
        Friend ReadOnly Property Form1_Button10_Click_Convert_All() As String
            Get
                Return ResourceManager.GetString("Form1_Button10_Click_Convert_All", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Convert Selected.
        '''</summary>
        Friend ReadOnly Property Form1_Button3_Click_Convert_Selected() As String
            Get
                Return ResourceManager.GetString("Form1_Button3_Click_Convert_Selected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  for MKV files ?.
        '''</summary>
        Friend ReadOnly Property Form1_Button4_Click__for_MKV_files__() As String
            Get
                Return ResourceManager.GetString("Form1_Button4_Click__for_MKV_files__", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Search folder.
        '''</summary>
        Friend ReadOnly Property Form1_Button4_Click_Search_folder() As String
            Get
                Return ResourceManager.GetString("Form1_Button4_Click_Search_folder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Search Results in : .
        '''</summary>
        Friend ReadOnly Property Form1_Button4_Click_Search_Results_in___() As String
            Get
                Return ResourceManager.GetString("Form1_Button4_Click_Search_Results_in___", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Would you like search in path .
        '''</summary>
        Friend ReadOnly Property Form1_Button4_Click_Would_you_like_search_in_path_() As String
            Get
                Return ResourceManager.GetString("Form1_Button4_Click_Would_you_like_search_in_path_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Deselect All.
        '''</summary>
        Friend ReadOnly Property Form1_Button6_Click_Deselect_All() As String
            Get
                Return ResourceManager.GetString("Form1_Button6_Click_Deselect_All", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select All.
        '''</summary>
        Friend ReadOnly Property Form1_Button6_Click_Select_All() As String
            Get
                Return ResourceManager.GetString("Form1_Button6_Click_Select_All", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error.
        '''</summary>
        Friend ReadOnly Property Form1_ListBox1__Error() As String
            Get
                Return ResourceManager.GetString("Form1_ListBox1__Error", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Duplicated files are not allowed in list.
        '''</summary>
        Friend ReadOnly Property Form1_ListBox1_DragDrop_Duplicated_files_are_not_allowed_in_list() As String
            Get
                Return ResourceManager.GetString("Form1_ListBox1_DragDrop_Duplicated_files_are_not_allowed_in_list", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
